# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 20cccca7e08c82ffe64e2766cf5dd07f075622a6517dec1567b8db91f08e098f280734ce5948bcb7443cdabd0e1425369646c4894297dd027ee8475cd78d2a8e

test:
  secret_key_base: 0434b0c90f9bd710f8ed49670fcb42bfb09f37cdf85e3d611a3be3999b25c8d0e2ca68ea48cea38fffaeaeb5eb35b0f674dbd97a6ccd4ef003475d82663bcd96

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
